### ISSUE TITLE
Any plan to publish it in the marketplace?

### ISSUE THREAD

**Issue by abuggin** [gennad/vscode-open-random-file#1]
Hi, I'd like to use this extension.
Do you have any plans to publish it or is it abandoned?
If it's abandoned, I might spend some time to fork it and publish it myself.
Cheers :tada:

**Comment by gennad** [comment]
Hey Bhudjo, thanks for bringing it up.
I did not know somebody would use it besides me. I will publish it!

**Comment by abuggin** [comment]
It's a small world :wink: 
:1st_place_medal:

**Comment by gennad** [comment]
https://marketplace.visualstudio.com/items?itemName=gennad.open-random-file
